# Generated by Django 3.2 on 2021-05-07 16:49

import ckeditor.fields
from django.db import migrations, models
import logistics.models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=150)),
                ('sender_address', models.CharField(max_length=500)),
                ('sender_phone_no', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('receiver_name', models.CharField(max_length=150)),
                ('receiver_address', models.CharField(max_length=500)),
                ('receiver_phone_no', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('tracking_no', models.BigIntegerField(default=logistics.models.random_numbers)),
                ('item_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ('-received_date',),
            },
        ),
    ]
