# Generated by Django 3.2.4 on 2021-08-10 06:53

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import logistics.models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=150)),
                ('sender_address', models.CharField(max_length=500)),
                ('sender_phone_no', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('receiver_name', models.CharField(max_length=150)),
                ('receiver_address', models.CharField(max_length=500)),
                ('receiver_phone_no', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('tracking_no', models.CharField(default=logistics.models.random_numbers, max_length=10)),
                ('item_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('received_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('delivery_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Received', 'Received'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Wrong Delivery Address', 'Wrong Delivery Address'), ('Unable to Locate Address', 'Unable to Locate Address'), ('Unable to Contact Receiver', 'Unable to Contact Receiver')], help_text='Update Delivery Status', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-received_date',),
            },
        ),
    ]
