# Generated by Django 3.2 on 2021-05-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_auto_20210504_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistic',
            name='receiver_phone_no',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='logistic',
            name='sender_phone_no',
            field=models.IntegerField(max_length=11),
        ),
    ]
