# Generated by Django 3.2.4 on 2021-06-21 09:31

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_alter_logistic_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistic',
            name='sender_phone_no',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
