# Generated by Django 3.2.4 on 2021-06-21 09:33

from django.db import migrations, models
import logistics.models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_alter_logistic_sender_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistic',
            name='tracking_no',
            field=models.CharField(default=logistics.models.random_numbers, max_length=10),
        ),
    ]
