# Generated by Django 3.2.4 on 2021-06-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0015_alter_logistic_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistic',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Wrong Delivery Address', 'Wrong Delivery Address'), ('Unable to Locate Address', 'Unable to Locate Address'), ('Unable to Contact Receiver', 'Unable to Contact Receiver')], default=True, help_text='Update Delivery Status', max_length=100, null=True),
        ),
    ]
