# Generated by Django 3.2.4 on 2021-06-02 17:26

import ckeditor.fields
from django.db import migrations, models
import shipping.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(help_text='input name', max_length=100)),
                ('items_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('shipping_fee', models.FloatField()),
                ('tracking_no', models.BigIntegerField(default=shipping.models.random_numbers)),
                ('received_date', models.DateField(null=True)),
                ('picked_on', models.DateField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ('received_date',),
            },
        ),
    ]
