# Generated by Django 3.2 on 2021-05-04 06:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingdetail',
            name='items_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
