# Generated by Django 3.2 on 2021-05-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_alter_shippingdetail_items_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingdetail',
            name='shipping_fee',
            field=models.FloatField(),
        ),
    ]
