# Generated by Django 3.2 on 2021-05-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistic',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='logistic',
            name='received_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
