# Generated by Django 3.2 on 2021-05-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_auto_20210504_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistic',
            name='receiver_phone_no',
            field=models.BigIntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='logistic',
            name='sender_phone_no',
            field=models.BigIntegerField(max_length=12),
        ),
    ]
