# Generated by Django 3.2 on 2021-05-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_auto_20210504_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistic',
            name='delivery_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='logistic',
            name='receiver_phone_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='logistic',
            name='sender_phone_no',
            field=models.IntegerField(),
        ),
    ]
