# Generated by Django 4.0.4 on 2022-05-28 14:26

import apps.common.generator
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixedPackage12Month',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investor_name', models.CharField(max_length=150)),
                ('phone_no', models.CharField(help_text='Contact phone number', max_length=11)),
                ('capital', models.FloatField(default=0)),
                ('returns_payout_date', models.DateField(null=True)),
                ('payout_status', models.CharField(default='Pending', max_length=20)),
                ('reference_no', models.IntegerField(default=apps.common.generator.random_numbers)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('percentage', models.CharField(default='200 %', max_length=5)),
                ('duration', models.CharField(default='12 months', max_length=10)),
                ('returns', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FixedPackage3Month',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investor_name', models.CharField(max_length=150)),
                ('phone_no', models.CharField(help_text='Contact phone number', max_length=11)),
                ('capital', models.FloatField(default=0)),
                ('returns_payout_date', models.DateField(null=True)),
                ('payout_status', models.CharField(default='Pending', max_length=20)),
                ('reference_no', models.IntegerField(default=apps.common.generator.random_numbers)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('percentage', models.CharField(default='45 %', max_length=5)),
                ('duration', models.CharField(default='3 months', max_length=10)),
                ('returns', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FixedPackage6Month',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investor_name', models.CharField(max_length=150)),
                ('phone_no', models.CharField(help_text='Contact phone number', max_length=11)),
                ('capital', models.FloatField(default=0)),
                ('returns_payout_date', models.DateField(null=True)),
                ('payout_status', models.CharField(default='Pending', max_length=20)),
                ('reference_no', models.IntegerField(default=apps.common.generator.random_numbers)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('percentage', models.CharField(default='90 %', max_length=5)),
                ('duration', models.CharField(default='6 months', max_length=10)),
                ('returns', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FixedPackage9Month',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investor_name', models.CharField(max_length=150)),
                ('phone_no', models.CharField(help_text='Contact phone number', max_length=11)),
                ('capital', models.FloatField(default=0)),
                ('returns_payout_date', models.DateField(null=True)),
                ('payout_status', models.CharField(default='Pending', max_length=20)),
                ('reference_no', models.IntegerField(default=apps.common.generator.random_numbers)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('percentage', models.CharField(default='140 %', max_length=5)),
                ('duration', models.CharField(default='9 months', max_length=10)),
                ('returns', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalaryPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_name', models.CharField(max_length=150)),
                ('phone_no', models.CharField(max_length=11)),
                ('capital', models.FloatField(default=0)),
                ('percentage', models.CharField(default='15 %', max_length=5)),
                ('duration', models.CharField(default='3 months', max_length=10)),
                ('investment_date', models.DateField(auto_now_add=True)),
                ('monthly_payment', models.FloatField()),
                ('first_payment', models.CharField(default='Pending', max_length=20)),
                ('payment_date_1', models.DateField(null=True)),
                ('second_payment', models.CharField(default='Pending', max_length=20)),
                ('payment_date_2', models.DateField(null=True)),
                ('third_payment', models.CharField(default='Pending', max_length=20)),
                ('payment_date_3', models.DateField(null=True)),
                ('reference_no', models.IntegerField(default=apps.common.generator.random_numbers)),
            ],
        ),
    ]
