# Generated by Django 4.0.4 on 2022-05-29 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logistic',
            options={'ordering': ('-received_date',), 'verbose_name': 'Logistic', 'verbose_name_plural': 'Logistics'},
        ),
    ]
