# Generated by Django 4.0.4 on 2022-06-07 09:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_logistic_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistic',
            name='item_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
