# Generated by Django 4.0.4 on 2022-05-28 14:26

import apps.common.generator
import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('sender_name', models.CharField(help_text='input name', max_length=100)),
                ('items_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('shipping_fee', models.FloatField()),
                ('tracking_no', models.BigIntegerField(default=apps.common.generator.random_numbers)),
                ('received_date', models.DateField(null=True)),
                ('picked_on', models.DateField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ('received_date',),
            },
        ),
    ]
