# Generated by Django 4.0.4 on 2022-06-08 13:16

import apps.common.generator
import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_alter_shippingdetail_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('sender_name', models.CharField(help_text='input name', max_length=100)),
                ('sender_email', models.EmailField(help_text='sender email', max_length=254)),
                ('phone_no', models.CharField(blank=True, help_text='sender phone number', max_length=11)),
                ('items_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('shipping_fee', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=100)),
                ('tracking_no', models.BigIntegerField(default=apps.common.generator.random_numbers)),
                ('received_date', models.DateField(null=True)),
                ('picked_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Received', 'Received'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Shipment undergoing US customs routine inspection', 'Shipment undergoing US customs routine inspection'), ('Shipment undergoing UK customs routine inspection', 'Shipment undergoing UK customs routine inspection'), ('Shipment undergoing CA customs routine inspection', 'Shipment undergoing CA customs routine inspection'), ('Shipment is now in transit to Lagos, Nigeria', 'Shipment is now in transit to Lagos, Nigeria')], default='In Transit', max_length=100)),
                ('attention', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Shipping Item',
                'verbose_name_plural': 'Shipping Items',
                'ordering': ('received_date',),
            },
        ),
        migrations.DeleteModel(
            name='ShippingDetail',
        ),
    ]
