# Generated by Django 3.2.4 on 2021-07-29 16:31

import computed_property.fields
from django.db import migrations, models
import forex.models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixedPackage12Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_name', models.CharField(max_length=150)),
                ('phone_no', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('email', models.EmailField(max_length=100)),
                ('capital', models.FloatField(default=0)),
                ('percentage', models.CharField(default='200 %', max_length=5)),
                ('duration', models.CharField(default='12 months', max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('returns', computed_property.fields.ComputedFloatField(compute_from='total_payment', editable=False)),
                ('returns_payout_date', models.DateField(null=True)),
                ('payout_status', models.CharField(default='Pending', max_length=20)),
                ('reference_no', models.IntegerField(default=forex.models.random_numbers)),
            ],
        ),
        migrations.CreateModel(
            name='FixedPackage3Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_name', models.CharField(max_length=150)),
                ('phone_no', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('email', models.EmailField(max_length=100)),
                ('capital', models.FloatField(default=0)),
                ('percentage', models.CharField(default='45 %', max_length=5)),
                ('duration', models.CharField(default='3 months', max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('returns', computed_property.fields.ComputedFloatField(compute_from='total_payment', editable=False)),
                ('returns_payout_date', models.DateField(null=True)),
                ('payout_status', models.CharField(default='Pending', max_length=20)),
                ('reference_no', models.IntegerField(default=forex.models.random_numbers)),
            ],
        ),
        migrations.CreateModel(
            name='FixedPackage6Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_name', models.CharField(max_length=150)),
                ('phone_no', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('email', models.EmailField(max_length=100)),
                ('capital', models.FloatField(default=0)),
                ('percentage', models.CharField(default='90 %', max_length=5)),
                ('duration', models.CharField(default='6 months', max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('returns', computed_property.fields.ComputedFloatField(compute_from='total_payment', editable=False)),
                ('returns_payout_date', models.DateField(null=True)),
                ('payout_status', models.CharField(default='Pending', max_length=20)),
                ('reference_no', models.IntegerField(default=forex.models.random_numbers)),
            ],
        ),
        migrations.CreateModel(
            name='FixedPackage9Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_name', models.CharField(max_length=150)),
                ('phone_no', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('email', models.EmailField(max_length=100)),
                ('capital', models.FloatField(default=0)),
                ('percentage', models.CharField(default='140 %', max_length=5)),
                ('duration', models.CharField(default='9 months', max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('returns', computed_property.fields.ComputedFloatField(compute_from='total_payment', editable=False)),
                ('returns_payout_date', models.DateField(null=True)),
                ('payout_status', models.CharField(default='Pending', max_length=20)),
                ('reference_no', models.IntegerField(default=forex.models.random_numbers)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_name', models.CharField(max_length=150)),
                ('phone_no', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('email', models.EmailField(max_length=100)),
                ('capital', models.FloatField(default=0)),
                ('percentage', models.CharField(default='15 %', max_length=5)),
                ('duration', models.CharField(default='3 months', max_length=10)),
                ('investment_date', models.DateField(auto_now_add=True)),
                ('monthly_payment', computed_property.fields.ComputedFloatField(compute_from='monthly_percentage', editable=False)),
                ('first_payment', models.CharField(default='Pending', max_length=20)),
                ('payment_date_1', models.DateField(null=True)),
                ('second_payment', models.CharField(default='Pending', max_length=20)),
                ('payment_date_2', models.DateField(null=True)),
                ('third_payment', models.CharField(default='Pending', max_length=20)),
                ('payment_date_3', models.DateField(null=True)),
                ('reference_no', models.IntegerField(default=forex.models.random_numbers)),
            ],
        ),
    ]
