# Generated by Django 3.2.4 on 2021-06-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0002_auto_20210602_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedpackage12month',
            name='email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixedpackage3month',
            name='email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixedpackage6month',
            name='email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixedpackage9month',
            name='email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarypackage',
            name='email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
