# Generated by Django 3.2.4 on 2021-06-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetail',
            name='gender',
            field=models.CharField(choices=[('mmale', 'male'), ('female', 'female'), ('others', 'others')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
