# Generated by Django 3.2.4 on 2021-06-19 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_shippingdetail_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingdetail',
            name='gender',
        ),
    ]
